### ISSUE TITLE
Shutdown issues with Ctrl-c

### ISSUE THREAD

**Issue by dcconner** [team-vigir/flexbe_behavior_engine#11]
I created a pull request that fixed some issues that I saw.
One of which due to : 

>`Interrupted mirror sleep.
Exception in thread Thread-28:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/conner/CNURobotics/src/flexbe_behavior_engine/flexbe_mirror/src/flexbe_mirror/flexbe_mirror.py", line 131, in _start_mirror
    self._execute_mirror()
  File "/home/conner/CNURobotics/src/flexbe_behavior_engine/flexbe_mirror/src/flexbe_mirror/flexbe_mirror.py", line 221, in _execute_mirror
    rospy.loginfo('Mirror finished with result ' + result)
TypeError: cannot concatenate 'str' and 'NoneType' objects
` 

The PR fixes that and lack of imported module.

One issue remains:

>  Exception in thread Thread-26 (most likely raised during interpreter shutdown):
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
  File "/usr/lib/python2.7/threading.py", line 754, in run
  File "/home/conner/CNURobotics/src/flexbe_behavior_engine/flexbe_mirror/src/flexbe_mirror/flexbe_mirror.py", line 131, in _start_mirror
  File "/home/conner/CNURobotics/src/flexbe_behavior_engine/flexbe_mirror/src/flexbe_mirror/flexbe_mirror.py", line 212, in _execute_mirror
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/smach/state_machine.py", line 359, in execute
  File "/home/conner/CNURobotics/src/flexbe_behavior_engine/flexbe_core/src/flexbe_core/core/lockable_state_machine.py", line 46, in _update_once
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/smach/state_machine.py", line 248, in _update_once
<type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'InvalidUserCodeError'
shutting down processing monitor...
... shutting down processing monitor complete

**Comment by pschillinger** [comment]
Thank you for fixing the shutdown exception!

And also thank you for already using FlexBE under Kinetic. I plan a thorough test of FlexBE (and also rqt_launchtree) under Jade and Kinetic in about two weeks when I am back home in Germany and have again access to my virtual machines.
